import { Liquor, FlavorProfile } from './liquorTypes';

export type { Liquor, FlavorProfile };

/**
 * Dynamically import all volume files and concatenate them.
 * Vite will code-split each dynamic import into a separate chunk.
 * The result is cached so subsequent calls resolve immediately.
 */
let _cache: Liquor[] | null = null;
let _promise: Promise<Liquor[]> | null = null;

export function loadAllLiquors(): Promise<Liquor[]> {
  if (_cache) return Promise.resolve(_cache);
  if (_promise) return _promise;

  _promise = Promise.all([
    import('./data/bourbons_vol1').then(m => m.BOURBONS_VOL1),
    import('./data/bourbons_vol2').then(m => m.BOURBONS_VOL2),
    import('./data/bourbons_vol3').then(m => m.BOURBONS_VOL3),
    import('./data/bourbons_vol4').then(m => m.BOURBONS_VOL4),
    import('./data/bourbons_vol5').then(m => m.BOURBONS_VOL5),
    import('./data/bourbons_vol6').then(m => m.BOURBONS_VOL6),
    import('./data/bourbons_vol7').then(m => m.BOURBONS_VOL7),
    import('./data/bourbons_vol8').then(m => m.BOURBONS_VOL8),
    import('./data/bourbons_vol9').then(m => m.BOURBONS_VOL9),
    import('./data/bourbons_vol10').then(m => m.BOURBONS_VOL10),
    import('./data/bourbons_vol11').then(m => m.BOURBONS_VOL11),
    import('./data/bourbons_vol12').then(m => m.BOURBONS_VOL12),
    import('./data/bourbons_vol13').then(m => m.BOURBONS_VOL13),
    import('./data/bourbons_vol14').then(m => m.BOURBONS_VOL14),
    import('./data/bourbons_vol15').then(m => m.BOURBONS_VOL15),
    import('./data/bourbons_vol16').then(m => m.BOURBONS_VOL16),
    import('./data/bourbons_vol17').then(m => m.BOURBONS_VOL17),
    import('./data/bourbons_vol18').then(m => m.BOURBONS_VOL18),
    import('./data/bourbons_vol19').then(m => m.BOURBONS_VOL19),
    import('./data/bourbons_vol20').then(m => m.BOURBONS_VOL20),
    import('./data/bourbons_vol21').then(m => m.BOURBONS_VOL21),
    import('./data/bourbons_vol22').then(m => m.BOURBONS_VOL22),
    import('./data/scotch_vol1').then(m => m.SCOTCH_VOL1),
    import('./data/scotch_vol2').then(m => m.SCOTCH_VOL2),
    import('./data/scotch_vol3').then(m => m.SCOTCH_VOL3),
    import('./data/scotch_vol4').then(m => m.SCOTCH_VOL4),
    import('./data/scotch_vol5').then(m => m.SCOTCH_VOL5),
    import('./data/scotch_vol6').then(m => m.SCOTCH_VOL6),
    import('./data/scotch_vol7').then(m => m.SCOTCH_VOL7),
    import('./data/irish_whiskey').then(m => m.IRISH_WHISKEY),
    import('./data/irish_whiskey_vol2').then(m => m.IRISH_WHISKEY_VOL2),
    import('./data/irish_whiskey_vol3').then(m => m.IRISH_WHISKEY_VOL3),
    import('./data/irish_whiskey_vol4').then(m => m.IRISH_WHISKEY_VOL4),
    import('./data/irish_whiskey_vol5').then(m => m.IRISH_WHISKEY_VOL5),
    import('./data/rye_whiskey').then(m => m.RYE_WHISKEY),
    import('./data/rye_whiskey_vol2').then(m => m.RYE_WHISKEY_VOL2),
    import('./data/rye_whiskey_vol3').then(m => m.RYE_WHISKEY_VOL3),
    import('./data/rye_whiskey_vol4').then(m => m.RYE_WHISKEY_VOL4),
    import('./data/rye_whiskey_vol5').then(m => m.RYE_WHISKEY_VOL5),
    import('./data/rye_whiskey_vol6').then(m => m.RYE_WHISKEY_VOL6),
    import('./data/canadian_whisky').then(m => m.CANADIAN_WHISKY),
    import('./data/canadian_whisky_vol2').then(m => m.CANADIAN_WHISKY_VOL2),
    import('./data/canadian_whisky_vol3').then(m => m.CANADIAN_WHISKY_VOL3),
    import('./data/canadian_whisky_vol4').then(m => m.CANADIAN_WHISKY_VOL4),
    import('./data/canadian_whisky_vol5').then(m => m.CANADIAN_WHISKY_VOL5),
    import('./data/vodka').then(m => m.VODKA),
    import('./data/vodka_vol2').then(m => m.VODKA_VOL2),
    import('./data/vodka_vol3').then(m => m.VODKA_VOL3),
    import('./data/vodka_vol4').then(m => m.VODKA_VOL4),
    import('./data/vodka_vol5').then(m => m.VODKA_VOL5),
    import('./data/vodka_vol6').then(m => m.VODKA_VOL6),
    import('./data/vodka_vol7').then(m => m.VODKA_VOL7),
    import('./data/gin').then(m => m.GIN),
    import('./data/gin_vol2').then(m => m.GIN_VOL2),
    import('./data/gin_vol3').then(m => m.GIN_VOL3),
    import('./data/gin_vol4').then(m => m.GIN_VOL4),
    import('./data/gin_vol5').then(m => m.GIN_VOL5),
    import('./data/gin_vol6').then(m => m.GIN_VOL6),
    import('./data/gin_vol7').then(m => m.GIN_VOL7),
    import('./data/rum').then(m => m.RUM),
    import('./data/rum_vol2').then(m => m.RUM_VOL2),
    import('./data/rum_vol3').then(m => m.RUM_VOL3),
    import('./data/rum_vol4').then(m => m.RUM_VOL4),
    import('./data/rum_vol5').then(m => m.RUM_VOL5),
    import('./data/rum_vol6').then(m => m.RUM_VOL6),
    import('./data/tequila_mezcal').then(m => m.TEQUILA_MEZCAL),
    import('./data/tequila_mezcal_vol2').then(m => m.TEQUILA_MEZCAL_VOL2),
    import('./data/tequila_mezcal_vol3').then(m => m.TEQUILA_MEZCAL_VOL3),
    import('./data/tequila_mezcal_vol4').then(m => m.TEQUILA_MEZCAL_VOL4),
    import('./data/tequila_mezcal_vol5').then(m => m.TEQUILA_MEZCAL_VOL5),
    import('./data/tequila_mezcal_vol6').then(m => m.TEQUILA_MEZCAL_VOL6),
    import('./data/brandy_cognac').then(m => m.BRANDY_COGNAC),
    import('./data/brandy_cognac_vol2').then(m => m.BRANDY_COGNAC_VOL2),
    import('./data/brandy_cognac_vol3').then(m => m.BRANDY_COGNAC_VOL3),
    import('./data/brandy_cognac_vol4').then(m => m.BRANDY_COGNAC_VOL4),
    import('./data/armagnac').then(m => m.ARMAGNAC),
    import('./data/armagnac_vol2').then(m => m.ARMAGNAC_VOL2),
    import('./data/armagnac_vol3').then(m => m.ARMAGNAC_VOL3),
    import('./data/japanese_whisky').then(m => m.JAPANESE_WHISKY),
    import('./data/japanese_whisky_vol2').then(m => m.JAPANESE_WHISKY_VOL2),
    import('./data/japanese_whisky_vol3').then(m => m.JAPANESE_WHISKY_VOL3),
    import('./data/japanese_whisky_vol4').then(m => m.JAPANESE_WHISKY_VOL4),
    import('./data/japanese_whisky_vol5').then(m => m.JAPANESE_WHISKY_VOL5),
    import('./data/liqueurs').then(m => m.LIQUEURS),
    import('./data/liqueurs_vol2').then(m => m.LIQUEURS_VOL2),
    import('./data/liqueurs_vol3').then(m => m.LIQUEURS_VOL3),
    import('./data/liqueurs_vol4').then(m => m.LIQUEURS_VOL4),
    import('./data/liqueurs_vol5').then(m => m.LIQUEURS_VOL5),
    import('./data/amaro').then(m => m.AMARO),
    import('./data/amaro_vol2').then(m => m.AMARO_VOL2),
    import('./data/amaro_vol3').then(m => m.AMARO_VOL3),
    import('./data/amaro_vol4').then(m => m.AMARO_VOL4),
    import('./data/absinthe_pastis').then(m => m.ABSINTHE_PASTIS),
    import('./data/absinthe_pastis_vol2').then(m => m.ABSINTHE_PASTIS_VOL2),
    import('./data/absinthe_pastis_vol3').then(m => m.ABSINTHE_PASTIS_VOL3),
    import('./data/aquavit').then(m => m.AQUAVIT),
    import('./data/aquavit_vol2').then(m => m.AQUAVIT_VOL2),
    import('./data/aquavit_vol3').then(m => m.AQUAVIT_VOL3),
    import('./data/genever').then(m => m.GENEVER),
    import('./data/genever_vol2').then(m => m.GENEVER_VOL2),
    import('./data/genever_vol3').then(m => m.GENEVER_VOL3),
    import('./data/grappa_eaux_de_vie').then(m => m.GRAPPA_EAUX_DE_VIE),
    import('./data/grappa_eaux_de_vie_vol2').then(m => m.GRAPPA_EAUX_DE_VIE_VOL2),
    import('./data/grappa_eaux_de_vie_vol3').then(m => m.GRAPPA_EAUX_DE_VIE_VOL3),
    import('./data/asian_spirits').then(m => m.ASIAN_SPIRITS),
    import('./data/asian_spirits_vol2').then(m => m.ASIAN_SPIRITS_VOL2),
    import('./data/asian_spirits_vol3').then(m => m.ASIAN_SPIRITS_VOL3),
    import('./data/cachaca_world_spirits').then(m => m.CACHACA_WORLD_SPIRITS),
    import('./data/cachaca_world_spirits_vol2').then(m => m.CACHACA_WORLD_SPIRITS_VOL2),
    import('./data/cachaca_world_spirits_vol3').then(m => m.CACHACA_WORLD_SPIRITS_VOL3),
    import('./data/vermouth_fortified').then(m => m.VERMOUTH_FORTIFIED),
    import('./data/vermouth_fortified_vol2').then(m => m.VERMOUTH_FORTIFIED_VOL2),
    import('./data/vermouth_fortified_vol3').then(m => m.VERMOUTH_FORTIFIED_VOL3),
    import('./data/bitters').then(m => m.BITTERS),
    import('./data/bitters_vol2').then(m => m.BITTERS_VOL2),
    import('./data/bitters_vol3').then(m => m.BITTERS_VOL3),
  ]).then(arrays => {
    _cache = arrays.flat();
    return _cache;
  });

  return _promise;
}
